### PR TITLE
Add tables and functions to find city by latitude and longitude

### PR DESCRIPTION
**Pull request by StephenMcConnel**
I haven't yet run the DefineFunctionsAndTriggers.sql script for the azure database.  I tested it locally on a reduced setup.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 44 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8yKN9D9-fnfekCQEU:-ME8yKN9D9-fnfekCQEV:brhop75) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L44)):*
> ```TSQL
> 			RETURN NEW;
> 		END IF;
> 	END IF;
> ```

Interesting that the previous function has an update but this addition doesn't (and you didn't update the update statement below for the new column). Do you think that means we can get rid of the update statement from the original portion?
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 109 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8ztab0Q1a33y4p9N3:-ME8ztab0Q1a33y4p9N4:b-jzucom) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L109)):*
> ```
> br_find_city_center_4_pages_read_fctn
> ```
This function doesn't  seem to be table-specific (as long as the table has the latitude, longitude, and city_center_id columns), right? So we should simplify the name.

Also, I'm unclear why pages_read gets a new trigger while book_or_shelf_opened had its trigger modified. Maybe the test schema only had it for book_or_shelf_opened? The bloomreader schema has both.
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 131 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8zMA_6b6jfDnp5RG9:-ME8zMA_6b6jfDnp5RGA:b-8c4bti) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L131)):*
> ```
> insert_city_center_pages_read
> ```
How do you feel about dropping the _pages_read from the name?
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 135 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9-VyL1ccrj05lOlCs:-ME9-VyL1ccrj05lOlCt:b-c37se4) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L135)):*
> ```TSQL
> 	ON bloomreadertest.pages_read
> 	FOR EACH ROW
> 	EXECUTE PROCEDURE public.br_find_city_center_4_pages_read_fctn();
> ```

I'm a little unclear whether this script is supposed to be getting the bloomreader schema ready or the bloomreadertest schema or both. 
Seems like a mixture.
If we are getting it ready for bloomreader, we should also have ones for bloomreaderbeta which is also basically production data.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 44 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8yKN9D9-fnfekCQEU:-ME90_L_Dv5KP793OjNy:bs3us1c) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L44)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Interesting that the previous function has an update but this addition doesn't (and you didn't update the update statement below for the new column). Do you think that means we can get rid of the update statement from the original portion?
</blockquote></details>

I think we can probably remove the update statement from the original portion.  I think this trigger function works without an explicit update because it's a "before" trigger, so modifying NEW is handled automatically.
I purposely didn't change the existing section, but am happy to do so.
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 109 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8ztab0Q1a33y4p9N3:-ME90zWk8f35-VSILQfA:b-7a48oq) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L109)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> br_find_city_center_4_pages_read_fctn
> ```
This function doesn't  seem to be table-specific (as long as the table has the latitude, longitude, and city_center_id columns), right? So we should simplify the name.

Also, I'm unclear why pages_read gets a new trigger while book_or_shelf_opened had its trigger modified. Maybe the test schema only had it for book_or_shelf_opened? The bloomreader schema has both.
</blockquote></details>

The difference between creating or modifying the trigger may well have been with the state of the test setup rather than the bloomreader(test|beta|) schema on the azure server.
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 131 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8zMA_6b6jfDnp5RG9:-ME93LTl58kyLyXNTzuN:b-896fix) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> insert_city_center_pages_read
> ```
How do you feel about dropping the _pages_read from the name?
</blockquote></details>

Done.
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 135 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9-VyL1ccrj05lOlCs:-ME91VgO5GP0kWoQ_W0-:bgq6l8w) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm a little unclear whether this script is supposed to be getting the bloomreader schema ready or the bloomreadertest schema or both. 
Seems like a mixture.
If we are getting it ready for bloomreader, we should also have ones for bloomreaderbeta which is also basically production data.
</blockquote></details>

This just reflects confusion/ignorance on my part.  I only looked at the bloomreadertest schema, and the pages_read table there did not have any triggers.  I see that the pages_read table in bloomreaderbeta has six triggers, including insert_location_uid and the table in bloomreader has three triggers, including insert_location_uid.
Should I do a new trigger or modify the existing ones as was done for bloomreadertest?  (If the trigger functions in the two/three schemas are the same for the correponding tables, I'll try doing a modify for both tables which would skip setting location_uid if city_center_id can be set.  But you can overrule this, of course.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 109 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8ztab0Q1a33y4p9N3:-ME95Yw1EILNEsnKfFxO:blheely) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L109)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The difference between creating or modifying the trigger may well have been with the state of the test setup rather than the bloomreader(test|beta|) schema on the azure server.
</blockquote></details>

See my comment below: bloomreadertest doesn't have any triggers on the pages_read table, and I didn't look at the other two tables.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 44 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8yKN9D9-fnfekCQEU:-ME98rDy0wQThIyMyr7J:btvkr2w) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L44)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think we can probably remove the update statement from the original portion.  I think this trigger function works without an explicit update because it's a "before" trigger, so modifying NEW is handled automatically.
I purposely didn't change the existing section, but am happy to do so.
</blockquote></details>

In fact, if we can do away with the UPDATE table statement, we can probably simplify things a great deal by having only one find_location_uid trigger function instead of one for each table.  :-)  This would require that all calling triggers be BEFORE INSERT, but that's probably true.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 44 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME8yKN9D9-fnfekCQEU:-ME9cB9SAVgw6F-nYFMw:b32s62e) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L44)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

In fact, if we can do away with the UPDATE table statement, we can probably simplify things a great deal by having only one find_location_uid trigger function instead of one for each table.  :-)  This would require that all calling triggers be BEFORE INSERT, but that's probably true.
</blockquote></details>

Wow, this is great!
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 135 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9-VyL1ccrj05lOlCs:-ME9ddE_4vzJh9WUtsDt:b-5hnh5m) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L135)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This just reflects confusion/ignorance on my part.  I only looked at the bloomreadertest schema, and the pages_read table there did not have any triggers.  I see that the pages_read table in bloomreaderbeta has six triggers, including insert_location_uid and the table in bloomreader has three triggers, including insert_location_uid.
Should I do a new trigger or modify the existing ones as was done for bloomreadertest?  (If the trigger functions in the two/three schemas are the same for the correponding tables, I'll try doing a modify for both tables which would skip setting location_uid if city_center_id can be set.  But you can overrule this, of course.
</blockquote></details>

Partly this depends on whether we want location_uid if we have city_center_id. In my thinking, we do. If we don't, they have to be part of the same trigger function, of course. If we do, the trigger function should be renamed to "and" instead of "or" and we may want the trigger names to be "insert_location_data" or similar.

Generally, I love love love getting down to one trigger function instead of one per table.

Of course, we won't be able to create the triggers on bloomreader and bloomreaderbeta until the new columns are there.
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 26 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9bxGr3trC41NzNEsh:-ME9bxGr3trC41NzNEsi:b-993mez) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/1371a3d5c7024067726c0b980317f4bbc86ebe67/schemas/public/DefineFunctionsAndTriggers.sql#L26)):*
> ```
> -- Thus, either NEW.city_center_id or NEW.location_uid is set by this function, but not
> -- both.
> ```
Was this JH's decision? I'm a bit surprised. I expected we would continue to populate location_uid in all cases. Else all our old queries will stop working as well.
___
*[schemas/public/tab2sql-admin1.sh, line 1 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9f7vH10d6w_sfOo28:-ME9f7vI4awi94KBN0gq:b-90x4uv) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/1371a3d5c7024067726c0b980317f4bbc86ebe67/schemas/public/tab2sql-admin1.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

What do you think of putting these scripts in a new top-level folder called scripts or bash scripts?
___
*[schemas/public/tab2sql-admin1.sh, line 47 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9fjSVCMyuKwiaAsVk:-ME9fjSVCMyuKwiaAsVl:b-yk97wo) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/1371a3d5c7024067726c0b980317f4bbc86ebe67/schemas/public/tab2sql-admin1.sh#L47)):*
> ```Shell
> 
> #echo psql --host=bloom-test-postgres-analytics.postgres.database.azure.com --port=5432 --username=silpgadmin@bloom-test-postgres-analytics --dbname=bloomsegment -f makeAndFillAdmin1.sql
> #psql --host=bloom-test-postgres-analytics.postgres.database.azure.com --port=5432 --username=silpgadmin@bloom-test-postgres-analytics --dbname=bloomsegment -f makeAndFillAdmin1.sql
> ```

I guess you verified we got the expected number of records for both tables??

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 135 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9-VyL1ccrj05lOlCs:-ME9nU6X-RfXgIeqZsCm:b-qbhun1) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/135e4935371bbe677e736a0364659b7ff5ac9fd1/schemas/public/DefineFunctionsAndTriggers.sql#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Partly this depends on whether we want location_uid if we have city_center_id. In my thinking, we do. If we don't, they have to be part of the same trigger function, of course. If we do, the trigger function should be renamed to "and" instead of "or" and we may want the trigger names to be "insert_location_data" or similar.

Generally, I love love love getting down to one trigger function instead of one per table.

Of course, we won't be able to create the triggers on bloomreader and bloomreaderbeta until the new columns are there.
</blockquote></details>

I've changed the function to set both, revised the comment and renamed it with "and".  I suppose we could split it into two separate functions and two sets of triggers, which might conceivably run in parallel.  But for now I'm leaving it as one function which implies one set of triggers.  I also renamed the actual triggers as suggested.
___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 26 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9bxGr3trC41NzNEsh:-ME9m0Z4AmiMTHxPnVxy:brpb73k) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/1371a3d5c7024067726c0b980317f4bbc86ebe67/schemas/public/DefineFunctionsAndTriggers.sql#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> -- Thus, either NEW.city_center_id or NEW.location_uid is set by this function, but not
> -- both.
> ```
Was this JH's decision? I'm a bit surprised. I expected we would continue to populate location_uid in all cases. Else all our old queries will stop working as well.
</blockquote></details>

No, I did this on my own.  I thought I better document it more explicitly to ensure getting a reaction.  Which I've gotten.  :-)
___
*[schemas/public/tab2sql-admin1.sh, line 1 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9f7vH10d6w_sfOo28:-ME9qh_PAbYbsBectix0:b9j2ozl) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/1371a3d5c7024067726c0b980317f4bbc86ebe67/schemas/public/tab2sql-admin1.sh#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What do you think of putting these scripts in a new top-level folder called scripts or bash scripts?
</blockquote></details>

Done.  I named the folder bash-scripts.
___
*[schemas/public/tab2sql-admin1.sh, line 47 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9fjSVCMyuKwiaAsVk:-ME9mQiT5pUpPJX2cLpi:bgvz2w0) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/1371a3d5c7024067726c0b980317f4bbc86ebe67/schemas/public/tab2sql-admin1.sh#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess you verified we got the expected number of records for both tables??
</blockquote></details>

Yes.  :-)
geography_regioncodes has the same number of rows as the original tab delimited file.
geography_city_centers has the same number of rows as the original tab delimited file + the 21 rows I added separately to handle towns near 180 degrees longitude.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[schemas/public/DefineFunctionsAndTriggers.sql, line 26 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/14#-ME9bxGr3trC41NzNEsh:-ME9u5330ZHAholZLsQ7:b-oq6y7f) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/1371a3d5c7024067726c0b980317f4bbc86ebe67/schemas/public/DefineFunctionsAndTriggers.sql#L26)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

No, I did this on my own.  I thought I better document it more explicitly to ensure getting a reaction.  Which I've gotten.  :-)
</blockquote></details>

I'm glad you did. : )

**Pull request merged**
