### PR TITLE
Fix IPv6 mapping (BL-10875)

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
I haven't changed anything on the real Postgres server yet, but I want to make these changes.  I hope that these changes not only update the IPv6 mapping, but make the whole thing easier to work with and understand.

Reviewing commit-by-commit will probably be helpful

> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-:-Mv-Zl5r0oohIIbaBGlg:bq58c4)* status: 0 of 12 files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Raised some questions/concerns. Might be easier to discuss than type async.

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-:-Mv-lfEn8ZTdTRihH8Vy:bt54bb5)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[bloomsegment.schema.backup, line 0 at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-eOmLDanD0ASTX77B:-Mv-eOmLDanD0ASTX77C:b5vo37j) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/bloomsegment.schema.backup#L0)):*
These changes will get lost next time we do a dump
___
*[2019 notes which may be obsolete/06 IP2CityRegionCountry Setup&Populate/04 IPV6 to IPV4/public.ip2ipv4.sql, line 3 at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-eYB68bFJZDZ0XOv9:-Mv-eYB68bFJZDZ0XOvA:b-m5ek3g) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/2019%20notes%20which%20may%20be%20obsolete/06%20IP2CityRegionCountry%20Setup%26Populate/04%20IPV6%20to%20IPV4/public.ip2ipv4.sql#L3)):*
> ```TSQL
> -- FUNCTION: public.ip2ipv4(character varying)
> 
> -- DROP FUNCTION public.ip2ipv4(character varying);
> ```

If this is the file in which we are really documenting this function, let's move it out of the 2019 notes folder to the new structure.
Or are we not using this function any more going forward? If that's the case, let's add that to a comment here.
___
*[schemas/public/functions/insert_ip_country_helper.sql, line 37 at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-gJbv6eqqjR1DeeT_:-Mv-gJbv6eqqjR1DeeTa:buch8cc) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/schemas/public/functions/insert_ip_country_helper.sql#L37)):*
> ```TSQL
>     -- but then we'd need to alter the column from bigint to numeric(39,0).
>     -- Another alternative is to have a v4 version of sm_tab and a v6 version of sm_tab,
>     -- but then we'd need to update all the places that read this.
> ```

So are you saying we don't have any cache for ipv6?
___
*[schemas/public/functions/ip_to_ipv4number.sql, line 22 at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-k8eh9PuHgHsk89lJ:-Mv-k8eh9PuHgHsk89lK:bhdyycb) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/schemas/public/functions/ip_to_ipv4number.sql#L22)):*
> ```TSQL
> -- EXCEPTION
> -- 	WHEN others THEN
> -- 		return 0;
> ```

We might need to talk about this.
We prevented exceptions since these triggers while postgres is doing its sync and it then prevents the sync from completing.

In hindsight, I would have done the whole warehouse completely differently where the tables from segment are pristine and untouched, but the tables we modify and report from are separate "copies". But that ship sailed.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[bloomsegment.schema.backup, line  at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-eOmLDanD0ASTX77B:-Mv1D200BdB2dnZpfsfY:brvoaw3) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/bloomsegment.schema.backup#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These changes will get lost next time we do a dump
</blockquote></details>

Ok, the comments here are basically a duplicate of my comments in the "2019 notes ..." folder. So, I'll just delete them here and let the ones in the ip2ipv4.sql file stand by itself.
___
*[2019 notes which may be obsolete/06 IP2CityRegionCountry Setup&Populate/04 IPV6 to IPV4/public.ip2ipv4.sql, line 3 at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-eYB68bFJZDZ0XOv9:-Mv19kpv9gDhE2J6vC6u:b-u21464) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/2019%20notes%20which%20may%20be%20obsolete/06%20IP2CityRegionCountry%20Setup%26Populate/04%20IPV6%20to%20IPV4/public.ip2ipv4.sql#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If this is the file in which we are really documenting this function, let's move it out of the 2019 notes folder to the new structure.
Or are we not using this function any more going forward? If that's the case, let's add that to a comment here.
</blockquote></details>

We still use this function. (Seemed too painful to get rid of it). Ok, I moved it to the new structure and did a bunch of rebasing.
___
*[schemas/public/functions/insert_ip_country_helper.sql, line 37 at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-gJbv6eqqjR1DeeT_:-Mv19swvCoCHNfAnOZ_X:b-t0gr6c) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/schemas/public/functions/insert_ip_country_helper.sql#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

So are you saying we don't have any cache for ipv6?
</blockquote></details>

Right, at least not yet.
___
*[schemas/public/functions/ip_to_ipv4number.sql, line 22 at r3](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-Mv-k8eh9PuHgHsk89lJ:-Mv1CbM37dOhJKEtr0jR:b-l89lf2) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/279a1b1ddd2ce1ebebc3e4d41549ad2b78c92aec/schemas/public/functions/ip_to_ipv4number.sql#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We might need to talk about this.
We prevented exceptions since these triggers while postgres is doing its sync and it then prevents the sync from completing.

In hindsight, I would have done the whole warehouse completely differently where the tables from segment are pristine and untouched, but the tables we modify and report from are separate "copies". But that ship sailed.
</blockquote></details>

Ok, gotcha. Happy to have it return 0 like the old code did too.

**Review by jsubloom — COMMENTED** [review]
I discovered find_location_uid_fctn, which needs to be updated too. It is highly similar to (a reduced form of) find_closest_city_and_location_uid.
So, I did the changes for that and did some squashing/rebasing of the history. Reviewable's pretty confusing now. But I can see that r4 is the new "1st" commit, r5 is the new "2nd" commit, and r6 is the new "3rd" commit.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-:-Mv5NcMP7fOtUI-jA4cG:b-2qd5qi)* status: 1 of 14 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 12 files at r4, 5 of 6 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22)* status: 14 of 102 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[2019 notes which may be obsolete/06 IP2CityRegionCountry Setup&Populate/03 CountryNametoPagesRead/BloomApp/ba_Create TRIGGER_InsertLocationUID - Launch.sql, line 1 at r9](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-MvPO8-31jJxNzUyQZzp:-MvPO8-31jJxNzUyQZzq:b-ocf6ra) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/d285475842b1cbf594a13881363bc2bc35f19532/2019%20notes%20which%20may%20be%20obsolete/06%20IP2CityRegionCountry%20Setup%26Populate/03%20CountryNametoPagesRead/BloomApp/ba_Create%20TRIGGER_InsertLocationUID%20-%20Launch.sql#L1)):*
> ```TSQL
> -- This file is deprecated. See schemas\bloomapp\triggers instead.
> ```

Or if you want me to delete the file, I can do that instead.
___
*[schemas/bloomreader/triggers/application_installed__insert_country_row.sql, line 3 at r9](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-MvPONJPCx91-1NL9r8J:-MvPONJPCx91-1NL9r8K:bhe2ez4) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/d285475842b1cbf594a13881363bc2bc35f19532/schemas/bloomreader/triggers/application_installed__insert_country_row.sql#L3)):*
> ```TSQL
> -- Trigger: insert_country_row
> 
> -- DROP TRIGGER IF EXISTS insert_country_row ON bloomreader.application_installed;
> ```

So one thing, I think depending on which version of pgAdmin you have, it will generate different SQL. Awkward.

The existing repo and my home desktop generated the other style, but my office desktop generated this style. It's supposed to be the latest pgAdmin and it reported PostgreSQL version 13, which is what our database is at, so.... I went with this syntax.  I updated these few existing files so that they'd be consistent syntax with the many new files added.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22)* status: 14 of 102 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[schemas/public/triggerFunctions/find_ip_location_uid_fctn.sql, line 1 at r9](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-MvPPH_l9Izos4Q5nJZ8:-MvPPH_l9Izos4Q5nJZ9:b-sl89gu) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/d285475842b1cbf594a13881363bc2bc35f19532/schemas/public/triggerFunctions/find_ip_location_uid_fctn.sql#L1)):*
> ```TSQL
> -- FUNCTION: public.find_ip_location_uid_fctn()
> ```

Argh. I am not a fan of this naming style. I wish _ip was a suffix. But for the insert_country_row versions, that's where it goes. 
Also, it's awkward that the insert_country_row versions explicitly spell out either ip or context_ip.  But for find_location_uid, the name find_location_uid is already used, with an implied "context_ip".

But tracking down and changing all the references to the 3 existing functions sounded like a lot more work than I wanted to do.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 68 of 68 files at r7, 19 of 19 files at r8, 28 of 28 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[2019 notes which may be obsolete/06 IP2CityRegionCountry Setup&Populate/03 CountryNametoPagesRead/BloomApp/ba_Create TRIGGER_InsertLocationUID - Launch.sql, line 1 at r9](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22#-MvPO8-31jJxNzUyQZzp:-MvPPCwL1XsET08d7sES:b-koi2be) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/d285475842b1cbf594a13881363bc2bc35f19532/2019%20notes%20which%20may%20be%20obsolete/06%20IP2CityRegionCountry%20Setup%26Populate/03%20CountryNametoPagesRead/BloomApp/ba_Create%20TRIGGER_InsertLocationUID%20-%20Launch.sql#L1)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Or if you want me to delete the file, I can do that instead.
</blockquote></details>

At this point, I want this task to die, as I'm sure you do. So I'm happy to go with whatever you already did. : )

**Review by andrew-polk — APPROVED** [review]
> Reviewed 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/22)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Pull request merged**
