### PR TITLE
Scripts to update mis-mapped IPv6 address locations (BL-10875)

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[schemas/public/functions/is_ip_valid.sql, line 1 at r1](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve-3X57mi4MSDLiPIP:-Mve-3X691Z9YDyPfixJ:bsy9z6e) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/b3e718fd89a85389ca67f69a49b387b5d922785c/schemas/public/functions/is_ip_valid.sql#L1)):*
> ```TSQL
> CREATE OR REPLACE FUNCTION public.is_ip_valid(ip_address character varying) RETURNS boolean
> ```

The changes to the first 4 files are all related to the discovery that multiple rows contain invalid IP addresses. So I wrote some handling around invalid IP's.

Actually, it would probably be easier to review the two new files at the end first (update*...), and then think about the invalid IP corner cases.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[schemas/public/functions/ip_to_location.sql, line 41 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve2j733cannNKJLcZZ:-Mve2j733cannNKJLcZ_:b-6a5doi) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/ip_to_location.sql#L41)):*
> ```TSQL
>     (public.ip_to_location('2800:98:1010:ef84:d38a:d0a7:3724:570a')).city='Guatemala City' AS pass1,
>     (public.ip_to_location('152.0.0.16')).city='Santo Domingo' AS pass2,
>     (public.ip_to_location('garbage input')).city='-' AS pass3
> ```

I can't figure out where '-' comes from.
Is that what we will enter for the city in the tables if the IP is not valid?
___
*[schemas/public/functions/normalize_ip.sql, line 62 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve31XD9IbJoQW8AO6Q:-Mve31XD9IbJoQW8AO6R:b-1ra8af) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/normalize_ip.sql#L62)):*
> ```TSQL
> 	WHEN invalid_text_representation THEN
> 		-- If the input is garbage, re-raise the original exception
> 		RAISE;
> ```

What happens if this gets raised?
___
*[schemas/public/functions/update_location_uids.sql, line 35 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve1nPx2SQu7nwHjKLj:-Mve1nPx2SQu7nwHjKLk:b-itol1g) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/update_location_uids.sql#L35)):*
> ```TSQL
>         WHERE (NOT %4$L) OR public.is_ipv6(ip_address)
>     ) AS b
>     WHERE a.%2$s = b.ip_address AND b.location_uid IS NOT NULL AND a.%3$s != b.location_uid
> ```

Why only when not null?



_Code quote:_
```TSQL
AND b.location_uid IS NOT NULL
```

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[schemas/public/functions/ip_to_location.sql, line 41 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve2j733cannNKJLcZZ:-Mvsr1Re8lAEs8A7A6Ye:blohw8e) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/ip_to_location.sql#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I can't figure out where '-' comes from.
Is that what we will enter for the city in the tables if the IP is not valid?
</blockquote></details>

The IP tables' first row maps 0 - [some number] to a hardcoded -, -, -, - row
___
*[schemas/public/functions/normalize_ip.sql, line 62 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve31XD9IbJoQW8AO6Q:-MvsrG061tFG3FxtX8pg:b-vcvlu7) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/normalize_ip.sql#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What happens if this gets raised?
</blockquote></details>

It rethrows the existing exception, and should go up the stack. The caller needs to catch it in its exception handler. It is called once, in ip_to_ipv6number(). That function has an exception handler which returns 0 for the IPv6 number.

The reason why I did it this way is because I don't want it to return the original untouched, and I didn't want to add a new rule that invalid input returns 0. (I guess returning null was another option which was semi-okay, but would make errors when using it ad-hoc more silent). But bubbling the error one level up and having ip_to_ipv6number return 0 made sense to me, since it and its siblings already have a requirement defined to return 0 on errors.
___
*[schemas/public/functions/update_location_uids.sql, line 35 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve1nPx2SQu7nwHjKLj:-Mvt7BDMBCql1rrNumfU:b-edqgo4) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/update_location_uids.sql#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why only when not null?
</blockquote></details>

That seems to be a paranoia sanity check. I checked two subqueries, they didn't actually return any null results. What would you like me to do with it?

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[schemas/public/functions/update_location_uids.sql, line 35 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve1nPx2SQu7nwHjKLj:-Mvtti6Q7CPiJZnJvh_p:bx13dqt) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/update_location_uids.sql#L35)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

That seems to be a paranoia sanity check. I checked two subqueries, they didn't actually return any null results. What would you like me to do with it?
</blockquote></details>

I was just thinking if we are going to the trouble to update, we might as well include all records for which we can get a valid value. But I guess if there are no nulls in practice, it doesn't really matter.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[schemas/public/functions/update_location_uids.sql, line 35 at r2](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-Mve1nPx2SQu7nwHjKLj:-MvxtktJDelTdOhNBnL4:b-pqd2ic) ([raw file](https://github.com/bloombooks/analytics-postgresql/blob/0949c2ecc9f2243e27f059ce8dc89d4f39771c1c/schemas/public/functions/update_location_uids.sql#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I was just thinking if we are going to the trouble to update, we might as well include all records for which we can get a valid value. But I guess if there are no nulls in practice, it doesn't really matter.
</blockquote></details>

Ok, I thought about this some. Since we call find_location_uid_helper, well that function is supposed to deal with nulls by creating a new entry for it and returning the location_uid. So, yeah a null value here would be very unexpected.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by jsubloom — COMMENTED** [review]
R3: I realized I didn't think about how the variables in the dynamic query should be properly escaped to avoid syntax errors and reduce SQL injection risk.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23#-:-MvyGLoc3XdUnVE-xORC:bh8qe6f)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/analytics-postgresql/23)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Pull request merged**
